version: "3.9"
services:
  web:
    image: "dependency_visualizer_image"
    container_name: "dependency_visualizer"
    build: .
    ports:
      - "5001:5000"
    environment:
      DB_HOST: "host.docker.internal"
      DB_PORT: "5433"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "Orion123"